version: "2"
services:
  es01-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment: 
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elastic
  
  kb-test:
    image: docker.elastic.co/kibana/kibana:7.14.0
    environment: 
      ELASTICSEARCH_HOSTS: http://es01-test:9200
    ports: 
      - 5601:5601
    networks:
      - elastic

networks: 
  elastic:
    driver: bridge