version: "2"
services:
  es01-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment: 
      - discovery.type=single-node
      - ELASTIC_PASSWORD=biaodi
      - xpack.security.enabled=true

    ports:
      - 9200:9200
    networks:
      - elastic
  
  kb-test:
    image: docker.elastic.co/kibana/kibana:7.14.0
    environment: 
      - ELASTICSEARCH_HOSTS=http://es01-test:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=biaodi

    ports: 
      - 5601:5601
    networks:
      - elastic

networks: 
  elastic:
    driver: bridge